project:
  type: website
  output-dir: docs

website:
  title: "Melissa May"
  favicon: images/homeicon.png
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
  page-footer:
    background: light # or 'dark'
    left: Created and maintained by Melissa May.
    right: Built with GitHub Pages and Quarto.

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

