project:
  type: website
  output-dir: docs

website:
  title: "Melissa May"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume

format:
  html:
    theme: minty
    css: styles.css
    toc: true
    page-layout: full

editor: visual

