---
title: "CSU Projects"
format: html
---

**Quantitative Reasoning - ESS 330**

In the Spring of 2025, I took a Quantitative Reasoning class based in R. The course has helped establish my baseline skills in open-source technologies like R and Quarto.

-   In this first lab assignment, we practiced comprehensively using our skills in R and Quarto so far. It was really helpful to be able to put everything together.
-   We also connected our websites in RStudio to a repository in Github, which helped strengthen my abilities and confidence with Git.
-   There were a lot of elements of style as well, which added a new interesting dimension, and a really fun way to use code to achieve results.
- I'm realizing that a large part of these coding projects could be troubleshooting and looking for simple errors that are throwing off the entire line of code. It's important to just stay patient and take your time going through the components of the website.

------------------------------------------------------------------------

**Skills for Undergraduate Participation in Ecological Research (SUPER)**

During the Fall 2024 and Spring 2025 semesters, I participated in the ESS program Skills for Undergraduate Participation in Ecological Research (SUPER). My research, in collaboration with Dr. Greg Newman, focused on citizen science and exploring participation patterns among users of the CitSci.org platform. Below is a collection of links to my work, which will be updated as it is made available!

**Analyzing Participation Patterns Across Citizen Science Projects on CitSci.org**

-   Explored various user participation patterns on the CitSci platform.
-   Conducted data analysis on project types, user engagement, and collaboration levels.
-   Generated hypotheses on how different factors like project tags, difficulty levels, and recommended age groups influence participation.
-   Collaborated with Dr. Greg Newman, co-creator of CitSci.org, to classify data into meaningful groups, improving user self-categorization.
-   Contributed to the development of a more intuitive platform for future project submissions.

**Links**

-   [CitSci](https://citsci.org/)
-   [CSU SUPER Program](https://warnercnr.colostate.edu/ess/ess-undergraduate-degree-tracks/ess-undergraduate-internships-research/super-home/)
